---
application:
  name: "spotify-proxy"
  project: "spotify-karaoke"
  organization: "QoveryCommunity"
routers:
- name: "main-spotify-proxy"
  routes:
  - application_name: "spotify-proxy"
    paths:
    - "/*"
