name: Merge request

on:
  pull_request:
    branches: [development]

  workflow_dispatch:

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm ci

      - name: Temporarily save node modules
        uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node_modules
          retention-days: 1

  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: node-modules

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve saved node modules
        uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: node_modules

      - name: Build
        run: npm build --aot

  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    needs: node-modules

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve saved node modules
        uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: node_modules

      - name: Linting
        run: npx nx run-many --target=lint --all=true

      - name: Unit tests
        run: npx nx test shared-interceptors shared-service shared-view web-lyrics-model web-lyrics-view

      - name: Chromatic
        run: npm run chromatic
