name: Merge request

on:
  pull_request:
    branches: [development]

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      #     - name: Cache node modules
      #       uses: actions/cache@v2
      #       with:
      #         path: node_modules
      #         key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      #         restore-keys: |
      #           ${{ runner.os }}-build-
      #           ${{ runner.os }}-
      #     - name: Install
      #       run: npm ci
      # build:
      #   name: Build package
      #   runs-on: ubuntu-latest
      #   needs: install
      #   steps:
      #     - name: Checkout
      #       uses: actions/checkout@v2
      #     - name: Load node_modules
      #       uses: actions/cache@v2
      #       with:
      #         path: node_modules
      #         key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      #     - name: Build
      #       run: npm run build:prod
      # analysis:
      #   name: Analysis
      #   runs-on: ubuntu-latest
      #   needs: install
      #   steps:
      #     - name: Checkout
      #       uses: actions/checkout@v2
      #       with:
      #         fetch-depth: 0 # 👈 Required to retrieve git history (chromatic)
      #     - name: Load node_modules
      #       uses: actions/cache@v2
      #       with:
      #         path: node_modules
      #         key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      #     - name: Linting
      #       run: npx nx run-many --target=lint --all=true
      #     - name: Unit tests
      #       run: npx nx test shared-interceptors shared-service shared-view web-lyrics-model web-lyrics-view
      - name: Chromatic
        if: "!contains('dependabot', github.head_ref)"
        run: echo ${{github.ref}} ${{github.head_ref}} ${{github.base_ref}}
        # run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes
